[package]
name = "file_downloader"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4.0.0"
features = "0.10.0"
futures-util = "0.3.30"
reqwest = { version = "0.11.6", features = ["stream"] }
tokio = { version = "1.0", features = ["full"] }
