name: ustudy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  google_fonts: 6.1.0
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  firebase_messaging: ^14.7.19
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  font_awesome_flutter: ^10.7.0
  multi_dropdown: ^2.1.4
  image_picker: ^1.0.7
  url_launcher: ^6.2.5
  percent_indicator: ^4.2.3
  dio: ^5.4.3+1

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/logo.png
