// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj8jpnqU9Xo1YXVFJh-wCdulweO5z--H8',
    appId: '1:581632635532:web:51ccda7d7adce6689a81a9',
    messagingSenderId: '581632635532',
    projectId: 'ustudy-96678',
    authDomain: 'ustudy-96678.firebaseapp.com',
    storageBucket: 'ustudy-96678.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-IfLNZQmq9SXKbvtzLnNujI6RYFwuNqM',
    appId: '1:581632635532:android:f3424539b219a6359a81a9',
    messagingSenderId: '581632635532',
    projectId: 'ustudy-96678',
    storageBucket: 'ustudy-96678.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU1IrzKOpyf4hkhEjWLFdm-d8fWH_ZdVQ',
    appId: '1:581632635532:ios:8d133b892817b9da9a81a9',
    messagingSenderId: '581632635532',
    projectId: 'ustudy-96678',
    storageBucket: 'ustudy-96678.appspot.com',
    iosBundleId: 'com.ustudy.ustudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU1IrzKOpyf4hkhEjWLFdm-d8fWH_ZdVQ',
    appId: '1:581632635532:ios:ff3183a48d21eb989a81a9',
    messagingSenderId: '581632635532',
    projectId: 'ustudy-96678',
    storageBucket: 'ustudy-96678.appspot.com',
    iosBundleId: 'com.ustudy.ustudy.RunnerTests',
  );
}
